import type { ActivityResponseDto } from "../types/activityTypes";

const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

export const mockActivities: ActivityResponseDto[] = [
  {
    id: "mock-activity-01",
    action: "UPDATE",
    entityName: "User",
    entityId: "mock-user-04",
    oldValues: JSON.stringify({ isActive: true }),
    newValues: JSON.stringify({ isActive: false }),
    ipAddress: "88.230.14.2",
    isSuccess: true,
    userId: "mock-user-01",
    userName: "esra.yilmaz",
    createdDate: hoursAgo(1),
  },
  {
    id: "mock-activity-02",
    action: "SYNC_PERMISSIONS",
    entityName: "Role",
    entityId: "c4188277-3e1e-4058-b593-577e4859339b",
    oldValues: JSON.stringify({ permissions: ["users.view"] }),
    newValues: JSON.stringify({ permissions: ["users.view", "users.edit"] }),
    ipAddress: "88.230.14.2",
    isSuccess: true,
    userId: "mock-user-01",
    userName: "esra.yilmaz",
    createdDate: hoursAgo(3),
  },
  {
    id: "mock-activity-03",
    action: "LOGIN",
    entityName: "Authentication",
    entityId: "mock-user-08",
    oldValues: null,
    newValues: null,
    ipAddress: "45.141.10.88",
    isSuccess: false,
    userId: "mock-user-08",
    userName: "gizem.arslan",
    createdDate: hoursAgo(4),
  },
  {
    id: "mock-activity-04",
    action: "CREATE",
    entityName: "User",
    entityId: "mock-user-10",
    oldValues: null,
    newValues: JSON.stringify({ username: "aylin.polat", email: "aylin.polat@myadmin.demo", role: "Viewer" }),
    ipAddress: "88.230.14.2",
    isSuccess: true,
    userId: "mock-user-01",
    userName: "esra.yilmaz",
    createdDate: hoursAgo(6),
  },
  {
    id: "mock-activity-05",
    action: "ASSIGN_ROLE",
    entityName: "UserRole",
    entityId: "mock-user-03",
    oldValues: JSON.stringify({ role: "Viewer" }),
    newValues: JSON.stringify({ role: "Editor" }),
    ipAddress: "88.230.14.2",
    isSuccess: true,
    userId: "mock-user-05",
    userName: "can.ozturk",
    createdDate: hoursAgo(9),
  },
  {
    id: "mock-activity-06",
    action: "LOGIN",
    entityName: "Authentication",
    entityId: "mock-user-08",
    oldValues: null,
    newValues: null,
    ipAddress: "45.141.10.88",
    isSuccess: false,
    userId: "mock-user-08",
    userName: "gizem.arslan",
    createdDate: hoursAgo(9.2),
  },
  {
    id: "mock-activity-07",
    action: "DELETE",
    entityName: "User",
    entityId: "mock-user-old-01",
    oldValues: JSON.stringify({ username: "eski.kullanici", email: "eski.kullanici@myadmin.demo" }),
    newValues: null,
    ipAddress: "88.230.14.2",
    isSuccess: true,
    userId: "mock-user-01",
    userName: "esra.yilmaz",
    createdDate: hoursAgo(14),
  },
  {
    id: "mock-activity-08",
    action: "CREATE",
    entityName: "Role",
    entityId: "mock-role-support",
    oldValues: null,
    newValues: JSON.stringify({ name: "Support", label: "Destek Ekibi" }),
    ipAddress: "88.230.14.2",
    isSuccess: true,
    userId: "mock-user-09",
    userName: "kaan.yildiz",
    createdDate: hoursAgo(20),
  },
  {
    id: "mock-activity-09",
    action: "UPDATE",
    entityName: "User",
    entityId: "mock-user-02",
    oldValues: JSON.stringify({ bio: null }),
    newValues: JSON.stringify({ bio: "İçerik operasyonları." }),
    ipAddress: "212.156.4.19",
    isSuccess: true,
    userId: "mock-user-02",
    userName: "deniz.kaya",
    createdDate: hoursAgo(27),
  },
  {
    id: "mock-activity-10",
    action: "SYNC_PERMISSIONS",
    entityName: "Role",
    entityId: "b1288277-3e1e-4058-b593-577e4859339c",
    oldValues: JSON.stringify({ permissions: [] }),
    newValues: JSON.stringify({ permissions: ["users.view"] }),
    ipAddress: "88.230.14.2",
    isSuccess: true,
    userId: "mock-user-01",
    userName: "esra.yilmaz",
    createdDate: hoursAgo(31),
  },
  {
    id: "mock-activity-11",
    action: "LOGIN",
    entityName: "Authentication",
    entityId: "mock-user-01",
    oldValues: null,
    newValues: null,
    ipAddress: "88.230.14.2",
    isSuccess: true,
    userId: "mock-user-01",
    userName: "esra.yilmaz",
    createdDate: hoursAgo(48),
  },
  {
    id: "mock-activity-12",
    action: "REVOKE_ROLE",
    entityName: "UserRole",
    entityId: "mock-user-06",
    oldValues: JSON.stringify({ role: "Editor" }),
    newValues: JSON.stringify({ role: "Viewer" }),
    ipAddress: "88.230.14.2",
    isSuccess: true,
    userId: "mock-user-05",
    userName: "can.ozturk",
    createdDate: hoursAgo(52),
  },
];

export const getMockActivities = (): ActivityResponseDto[] => mockActivities.map((activity) => ({ ...activity }));
